name: 'Settings Tray Translations'
type: module
description: 'Provides the ability for Settings Tray to handle translations.'
package: Core
version: VERSION
core: 8.x
dependencies:
  - 'drupal:settings_tray'
  - 'druapl:config_translation'
  - 'drupal:system (>= 8.5)'
